import Link from 'next/link';

const courses=[
 {title:'Cryptocurrency Fundamentals',level:'Beginner',duration:'4–6 weeks',lessons:14,desc:'Bitcoin, blockchain, wallets, exchanges, stablecoins, market cap, FDV, liquidity, tokenomics and security.'},
 {title:'Technical Analysis Masterclass',level:'Intermediate',duration:'6–8 weeks',lessons:15,desc:'Candlesticks, market structure, support and resistance, trends, volume, indicators, price action and TradingView.'},
 {title:'Crypto Risk Management',level:'All levels',duration:'3–4 weeks',lessons:10,desc:'Position sizing, stop loss, take profit, risk/reward, capital preservation, journaling and trading psychology.'},
 {title:'Advanced Crypto Trading',level:'Advanced',duration:'8–10 weeks',lessons:9,desc:'Liquidity concepts, order blocks, fair value gaps, volume analysis, multi-timeframe analysis, backtesting and strategy design.'},
];
export default function Courses(){return <><header className="site-header"><div className="container nav"><Link href="/" className="brand"><span className="logo">TC</span><span>THOOZANE CRYPTO<small>TRADER • ACADEMY</small></span></Link><div className="navactions"><Link className="btn btn-ghost" href="/login">Student Login</Link><Link className="btn btn-primary" href="/register">Get Started</Link></div></div></header><main><section className="section" style={{borderTop:0,paddingTop:90}}><div className="container"><div className="eyebrow">THOOZANE ACADEMY</div><h1 style={{fontFamily:'Space Grotesk',fontSize:'clamp(44px,6vw,72px)',letterSpacing:'-.05em',margin:'15px 0'}}>Learn crypto with structure.</h1><p className="section-intro">Choose a learning path designed around knowledge, practical analysis and risk awareness.</p><div className="courses" style={{marginTop:35}}>{courses.map(c=><article className="course" key={c.title}><div className="course-top"><h3>{c.title}</h3><span className="badge">{c.level}</span></div><p>{c.desc}</p><div className="meta"><span>{c.lessons} modules</span><span>{c.duration}</span><span>Quizzes</span></div><Link href="/register">Enroll & learn →</Link></article>)}</div></div></section></main><footer className="footer"><div className="container footer-grid"><span>© 2026 Thoozane Crypto Trader</span><span>Education First. Risk Management Always.</span></div></footer></>}
