import { PrismaClient, LessonType } from '@prisma/client';
import bcrypt from 'bcryptjs';
const db=new PrismaClient();
const catalog=[
 {title:'Cryptocurrency Fundamentals',slug:'cryptocurrency-fundamentals',description:'Build a strong foundation in Bitcoin, blockchain, wallets, exchanges, tokenomics, liquidity and security.',lessons:['What is Cryptocurrency?','Bitcoin Explained','Blockchain Fundamentals','Wallets','Exchanges','Stablecoins','Market Cap','Circulating Supply','Total Supply','FDV','Liquidity','Tokenomics','Security','Common Crypto Scams']},
 {title:'Technical Analysis Masterclass',slug:'technical-analysis-masterclass',description:'Learn market structure, price action, indicators, chart patterns and multi-timeframe analysis.',lessons:['Candlestick Basics','Market Structure','Support & Resistance','Trends','Breakouts','Liquidity','Volume','Moving Averages','RSI','MACD','Fibonacci','Price Action','Chart Patterns','Multi-Timeframe Analysis','TradingView']},
 {title:'Crypto Risk Management',slug:'crypto-risk-management',description:'Protect capital with position sizing, stop loss, risk/reward, trading journals and discipline.',lessons:['Position Sizing','Stop Loss','Take Profit','Risk/Reward','Maximum Daily Loss','Capital Preservation','Trading Journal','Emotional Control','Avoid Overtrading','Avoid Revenge Trading']},
 {title:'Advanced Crypto Trading',slug:'advanced-crypto-trading',description:'Develop a repeatable trading framework using liquidity, order blocks, FVGs, volume and backtesting.',lessons:['Market Structure','Liquidity Concepts','Order Blocks','Fair Value Gaps','Volume Analysis','Multi-Timeframe Analysis','Trading Plans','Backtesting','Strategy Development']}
];
async function main(){
 const passwordHash=await bcrypt.hash('ChangeMe123!',12);
 await db.user.upsert({where:{email:'admin@thoozanecrypto.com'},update:{role:'ADMIN'},create:{name:'Thoozane Admin',email:'admin@thoozanecrypto.com',passwordHash,role:'ADMIN'}});
 for(const c of catalog){const course=await db.course.upsert({where:{slug:c.slug},update:{title:c.title,description:c.description,published:true},create:{title:c.title,slug:c.slug,description:c.description,published:true}}); const mod=await db.module.upsert({where:{id:`seed-${course.id}`},update:{title:'Core Curriculum',position:1},create:{id:`seed-${course.id}`,title:'Core Curriculum',position:1,courseId:course.id}}); for(let i=0;i<c.lessons.length;i++){const slug=c.lessons[i].toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''); await db.lesson.upsert({where:{moduleId_slug:{moduleId:mod.id,slug}},update:{title:c.lessons[i],position:i+1,type:LessonType.TEXT,content:`<h2>${c.lessons[i]}</h2><p>This lesson is part of the Thoozane Crypto Trader curriculum. Study the concept carefully, take notes, and apply risk-aware thinking to every example.</p><p><strong>Education First. Risk Management Always.</strong></p>`},create:{title:c.lessons[i],slug,position:i+1,type:LessonType.TEXT,content:`<h2>${c.lessons[i]}</h2><p>This lesson is part of the Thoozane Crypto Trader curriculum. Study the concept carefully, take notes, and apply risk-aware thinking to every example.</p><p><strong>Education First. Risk Management Always.</strong></p>`,moduleId:mod.id}}); }}
}
main().finally(()=>db.$disconnect());
