import Link from 'next/link';
import { redirect } from 'next/navigation';
import { db } from '@/lib/db';
import { session } from '@/lib/auth';

export default async function Dashboard(){
  const s=await session(); if(!s) redirect('/login');
  const user=await db.user.findUnique({where:{id:s.id},include:{enrollments:{include:{course:{include:{modules:{include:{lessons:true}}}}}},certificates:{include:{course:true}}}});
  if(!user) redirect('/login');
  const progress=await db.lessonProgress.findMany({where:{userId:user.id,completed:true}});
  const total=user.enrollments.reduce((n,e)=>n+e.course.modules.reduce((m,mod)=>m+mod.lessons.length,0),0);
  const pct=total?Math.round(progress.length/total*100):0;
  const next=user.enrollments.flatMap(e=>e.course.modules.flatMap(m=>m.lessons)).find(l=>!progress.some(p=>p.lessonId===l.id));
  return <main><header className="site-header"><div className="container nav"><Link href="/" className="brand"><span className="logo">TC</span><span>THOOZANE CRYPTO<small>STUDENT ACADEMY</small></span></Link><Link className="btn btn-ghost" href="/">Exit dashboard</Link></div></header><section className="dashboard"><div className="container"><div className="dashgrid"><aside className="sidebar"><a className="active" href="#">Overview</a><a href="#courses">My Courses</a><a href="#certificates">Certificates</a><a href="/resources">Resources</a><a href="/market-tools">Market Tools</a><a href="#profile">Profile & Settings</a></aside><div><div style={{marginBottom:25}}><div className="eyebrow">STUDENT DASHBOARD</div><h1 style={{fontFamily:'Space Grotesk',fontSize:42,margin:'10px 0'}}>Welcome back, {user.name.split(' ')[0]}.</h1><p className="section-intro">Keep learning. Build your knowledge one lesson at a time.</p></div><div className="stats"><div className="stat"><span>Active courses</span><b>{user.enrollments.length}</b></div><div className="stat"><span>Lessons completed</span><b>{progress.length}/{total}</b></div><div className="stat"><span>Overall progress</span><b>{pct}%</b></div><div className="stat"><span>Certificates</span><b>{user.certificates.length}</b></div></div>{next&&<div className="contact" style={{marginTop:25}}><div><div className="eyebrow">CONTINUE LEARNING</div><h2 style={{fontSize:26}}>{next.title}</h2><p>Resume your next unfinished lesson.</p></div><Link className="btn btn-primary" href={`/courses/${next.moduleId}/lessons/${next.slug}`}>Continue →</Link></div>}<div className="section" id="courses" style={{padding:'50px 0 0',border:0}}><div className="section-head"><div><div className="eyebrow">MY COURSES</div><h2 style={{fontSize:30}}>Your courses</h2></div><Link className="btn btn-ghost" href="/courses">Browse all →</Link></div><div className="courses">{user.enrollments.map(e=><article className="course" key={e.id}><div className="course-top"><h3>{e.course.title}</h3><span className="badge">{e.status}</span></div><p>{e.course.description}</p><div className="meta"><span>{e.course.modules.length} modules</span><span>{e.course.modules.reduce((n,m)=>n+m.lessons.length,0)} lessons</span></div><Link href={`/courses/${e.course.slug}`}>Open course →</Link></article>)}</div></div><div className="section" id="certificates" style={{padding:'50px 0 0',border:0}}><div className="eyebrow">CERTIFICATES</div><h2 style={{fontSize:30}}>Your achievements</h2><div className="resource-grid" style={{marginTop:20}}>{user.certificates.length?user.certificates.map(c=><article className="resource" key={c.id}><h3>{c.course.title}</h3><p>{c.certificateNumber}</p><Link href={`/verify/certificate/${c.certificateNumber}`}>Verify certificate →</Link></article>):<article className="resource"><h3>No certificates yet</h3><p>Complete your course requirements to earn your first certificate.</p></article>}</div></div></div></div></div></section></main>
}